6. 連想配列, 多次元配列、課題1の提出
yuta10200831/6.docker-template pull request #1
Opened 2023-07-09 08:48 UTC by yuta10200831

## 作業対象
作業をした教材のURL or 作成したページのURLなどを記載する
[作業をした教材のURL]
https://www.notion.so/6-186d36bf4f8843929dd7c970686582cb
[作成したページのURL(index.php)]
(http://localhost:8080/)

## 作業詳細
6.連想配列,多次元配列　課題1の提出
連想配列を用いて
ブラジル: 100人
日本: 150人
スペイン: 50000人
を出力。

<img width="1735" alt="スクリーンショット 2023-07-09 17 47 32" src="https://github.com/yuta10200831/6.docker-template/assets/124555669/3cf063de-bd5f-443f-b873-878d3f0a2965">

2023-07-10 02:17 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-07-10 02:17 UTC, KatsuyaTanaka95 commented on src/public/index.php
> +        if ($animalNum > 1) {
2以上という条件にしましょう！！！

2023-07-10 12:55 UTC, yuta10200831 commented on src/public/index.php
> +        if ($animalNum > 1) {
修正しました！

2023-07-10 12:55 UTC, yuta10200831 commented
if文の内容を２以上に変更しました！！

2023-07-11 04:36 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-07-11 04:36 UTC, KatsuyaTanaka95 commented on src/public/index.php
> +        if ($animalNum > 2) {
こちら2以上ではなく、2より大きいになってしまってます！😭
ブラウザで表示が仕様通りになっているかも確認してから提出するようにしましょう！！！😭

2023-07-11 12:02 UTC, yuta10200831 commented on src/public/index.php
> +        if ($animalNum > 2) {
修正しました！

2023-07-11 12:04 UTC, yuta10200831 commented
2以上に修正しました！
申し訳ありませんでした、ブラウザのスクショ送付します。
<img width="1744" alt="スクリーンショット 2023-07-11 21 02 40" src="https://github.com/yuta10200831/6.docker-template/assets/124555669/000cf54d-0eeb-4eb4-8c36-347fd4176938">

また、こないだお話したコミットする際にパスワードを求められる場合のスクショも送付します。
これ、なんかおかしいのですかね？？
ご確認お願いします。
<img width="1735" alt="スクリーンショット 2023-07-11 21 01 52" src="https://github.com/yuta10200831/6.docker-template/assets/124555669/9762a9ba-539c-4976-b65c-f6dd796624ca">

2023-07-12 05:45 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeいただけると助かります！🙆🙋😊🌟💫

2023-07-12 10:10 UTC, merged